CREATE TABLE backup_schedules (
  id BIGINT NOT NULL AUTO_INCREMENT,
  routine VARCHAR(255) NOT NULL,
  date_start DATETIME,
  residual TINYINT DEFAULT 3,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);